
# services
services:
  front-end: 
    build:
      context: ./back-end
      dockerfile: Dockerfile 
    # image: softy-pinko-back-end:task4
    # ports:
    #   - "5252:5252"
    environment:
      - HTTP_PROXY=http://localhost:80
    expose:
      - "9000"
  back-end: 
    build:
      context: ./front-end
      dockerfile: Dockerfile 
    # image: softy-pinko-front-end:task4
    # ports:
    #   - "9000:9000"
    environment:
      - HTTP_PROXY=http://localhost:80
    expose:
      - "5252"
  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
# build, context, dockerfile

# image

# ports

#depends on
