
# services
services:
  back-end:
    image: softy-pinko/back-end 
    build:
      context: ./back-end
      dockerfile: Dockerfile 
    # image: softy-pinko-front-end:task4
    ports:
      - "5252"
  front-end: 
    image: softy-pinko/front-end
    build:
      context: ./front-end
      dockerfile: Dockerfile 
    # image: softy-pinko-back-end:task4
    ports:
      - "9000" 
  proxy:
    image: softy-pinko/proxy
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
# build, context, dockerfile

# image

# ports

#depends on
